//
//  BTFThemeKeys.h
//  Butterfly
//
//  Created by Marco Bambini on 15/07/15.
//  Copyright (c) 2015 Marco Bambini. All rights reserved.
//

// HEADER
#define BTFKEY_HEADER_BORDER_COLOR			@"HEADER_BORDER_COLOR"
#define BTFKEY_HEADER_BACKGROUND_COLOR		@"HEADER_BACKGROUND_COLOR"
#define BTFKEY_HEADER_DETACH_IMAGE			@"HEADER_DETACH_IMAGE"
#define BTFKEY_HEADER_ATTACH_IMAGE			@"HEADER_ATTACH_IMAGE"

// NAVIGATION
#define BTFKEY_NAV_TEXT_COLOR				@"NAVIGATION_TEXTPLAIN_COLOR"
#define BTFKEY_NAV_BOLD_COLOR				@"NAVIGATION_TEXTBOLD_COLOR"
#define BTFKEY_NAV_SELECTION_COLOR			@"NAVIGATION_SELECTION_COLOR"
#define BTFKEY_NAV_BACKGROUND_COLOR			@"NAVIGATION_BACKGROUND_COLOR"

// RULER
#define BTFKEY_RULER_BACKGROUND_COLOR		@"RULER_BACKGROUND_COLOR"
#define BTFKEY_RULER_TEXT_COLOR				@"RULER_TEXTPLAIN_COLOR"
#define BTFKEY_RULER_ERROR_COLOR			@"RULER_TEXTERROR_COLOR"
#define BTFKEY_RULER_BORDER_COLOR			@"RULER_BORDER_COLOR"
#define BTFKEY_RULER_BORDER_WIDTH			@"RULER_BORDER_WIDTH"
#define BTFKEY_RULER_WIDTH					@"RULER_WIDTH"

// SCOPE
#define BTFKEY_SCOPE_ALPHA					@"SCOPE_ALPHA"

// CODEEDITOR
#define BTFKEY_INSET_VALUE					@"CODEEDITOR_INSET_VALUE"
#define BTFKEY_BACKGROUND_COLOR				@"CODEEDITOR_BACKGROUND_COLOR"
#define BTFKEY_FONT							@"CODEEDITOR_PLAIN_FONT"
#define BTFKEY_BOLD_FONT					@"CODEEDITOR_BOLD_FONT"
#define BTFKEY_FONT_SIZE					@"CODEEDITOR_FONT_SIZE"
#define BTFKEY_SELECTION_COLOR				@"CODEEDITOR_SELECTION_COLOR"
#define BTFKEY_CURSOR_COLOR					@"CODEEDITOR_CURSOR_COLOR"
#define BTFKEY_PLAIN_COLOR					@"CODEEDITOR_PLAIN_COLOR"
#define BTFKEY_IDENTIFIER_COLOR				@"CODEEDITOR_IDENTIFIER_COLOR"
#define BTFKEY_COMMENTS_COLOR				@"CODEEDITOR_COMMENTS_COLOR"
#define BTFKEY_STRINGS_COLOR				@"CODEEDITOR_STRINGS_COLOR"
#define BTFKEY_NUMBERS_COLOR				@"CODEEDITOR_NUMBERS_COLOR"
#define BTFKEY_KEYWORDS_COLOR				@"CODEEDITOR_KEYWORDS_COLOR"
#define BTFKEY_MACROS_COLOR					@"CODEEDITOR_MACROS_COLOR"
#define BTFKEY_SPECIAL_COLOR				@"CODEEDITOR_SPECIAL_COLOR"
#define BTFKEY_CLASS_COLOR					@"CODEEDITOR_CLASS_COLOR"
#define BTFKEY_FUNCTION_COLOR				@"CODEEDITOR_FUNCTION_COLOR"
#define BTFKEY_VAR_COLOR					@"CODEEDITOR_VAR_COLOR"
#define BTFKEY_CONST_COLOR					@"CODEEDITOR_CONST_COLOR"
#define BTFKEY_ENUM_COLOR					@"CODEEDITOR_ENUM_COLOR"
#define BTFKEY_MODULES_COLOR				@"CODEEDITOR_MODULES_COLOR"
#define BTFKEY_ERROR_COLOR					@"CODEEDITOR_ERROR_COLOR"
