Name: "gravity"
Language: "C++|0.4"
Version: "1.0.0"
EnableWarningsAsErrors: false
IncludePaths: [
	"compiler/"
	"optionals/"
	"runtime/"
	"shared/"
	"utils/"
]
Source: [
	"compiler/gravity_ast.c"
	"compiler/gravity_codegen.c"
	"compiler/gravity_compiler.c"
	"compiler/gravity_ircode.c"
	"compiler/gravity_lexer.c"
	"compiler/gravity_optimizer.c"
	"compiler/gravity_parser.c"
	"compiler/gravity_semacheck1.c"
	"compiler/gravity_semacheck2.c"
	"compiler/gravity_symboltable.c"
	"compiler/gravity_token.c"
	"compiler/gravity_visitor.c"
	"optionals/gravity_opt_env.c"
	"optionals/gravity_opt_file.c"
	"optionals/gravity_opt_json.c"
	"optionals/gravity_opt_math.c"
	"runtime/gravity_core.c"
	"runtime/gravity_vm.c"
	"shared/gravity_hash.c"
	"shared/gravity_memory.c"
	"shared/gravity_value.c"
	"utils/gravity_debug.c"
	"utils/gravity_json.c"
	"utils/gravity_utils.c"
]